apiVersion: v1
kind: Service
metadata:
  name: nats-external
  namespace: default
spec:
  type: ExternalName
  externalName: nats.k3s-demo_default # Docker internal DNS name for the nats container
  ports:
  - port: 4222
